/**Redux types**/

// Tables types
export const GET_ALL_COLUMNS = 'GET_ALL_COLUMNS';
export const MOVE_ITEM_FROM_COLUMN_TO_COLUMN = 'MOVE_ITEM_FROM_COLUMN_TO_COLUMN';
export const ADD_TASK_TO_COLUMNS = 'ADD_TASK_TO_COLUMNS';
export const UPDATE_ITEMS_INDEX_AT_COLUMNS = 'UPDATE_ITEMS_INDEX_AT_COLUMNS';
